language: perl

perl:
  - "5.8"
#  - "5.10"
#  - "5.12"
#  - "5.14"
#  - "5.16"
#  - "5.18"
#  - "5.18-shrplib"
#  - "5.20"
#  - "5.20-shrplib"
#  - "5.22"
#  - "5.22-shrplib"
#  - "5.24"
#  - "5.24-shrplib"
#  - "5.26"
#  - "5.26-shrplib"
#  - "5.28"

matrix:
  include:
    - perl: system_precise
      dist: precise
      addons: &addons
        apt:
          packages:
            - perl
            - cpanminus
    - perl: system_trusty
      dist: trusty
      addons:
        <<: *addons
    - perl: system_xenial
      dist: xenial
      addons:
        <<: *addons
    - perl: "5.18.4.1"
      os: windows
      language: shell
      env: TRAVIS_PERL_VERSION="5.18.4.1"

before_install:
  - if [[ $TRAVIS_PERL_VERSION =~ ^system ]]; then export PERL5LIB=$HOME/perl5/lib/perl5; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cinst StrawberryPerl --version "$TRAVIS_PERL_VERSION" --allow-empty-checksums; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export PATH="/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Strawberry/c/bin:$PATH"; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then perl -V; cpan -T App::cpanminus; fi

install:
  - perl '-MExtUtils::MakeMaker 6.68' -e '' || cpanm --quiet --notest ExtUtils::MakeMaker@6.68
  - perl '-MCPAN::Meta 2.112580' -e '' || cpanm --quiet --notest CPAN::Meta@2.112580
  - cpanm --quiet --notest --skip-satisfied --installdeps --with-configure --with-develop --with-recommends --with-suggests .

script:
  - perl Makefile.PL
  - perl -MConfig -e "system({$Config{make}} $Config{make}, @ARGV); exit((($? >> 8) | ($? & 127)) & 255)"
  - perl -MConfig -e "system({$Config{make}} $Config{make}, @ARGV); exit((($? >> 8) | ($? & 127)) & 255)" test TEST_VERBOSE=1
